//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHMCSDelhi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EnquiryMaster
    {
        public int EnquieyId { get; set; }
        public string Name { get; set; }
        public string Emailid { get; set; }
        public string MobileNo { get; set; }
        public string RequestedURL { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Active { get; set; }
        public string UserMessage { get; set; }
        public string AdminReply { get; set; }
    }
}
